name: build java images

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "java/**"
      - ".github/workflows/java.yml"
  pull_request:
    paths:
      - "java/**"
      - ".github/workflows/java.yml"

jobs:
  build:
    name: "java_${{ matrix.vendor }}_${{ matrix.version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - vendor: corretto
            version: "21"
          - vendor: corretto
            version: "25"
          - vendor: zulu
            version: "21"
          - vendor: zulu
            version: "25"
          - vendor: liberica
            version: "21"
          - vendor: liberica
            version: "25"
          - vendor: microsoft
            version: "21"
          - vendor: microsoft
            version: "25"
          - vendor: temurin
            version: "21"
          - vendor: temurin
            version: "25"
          - vendor: graalvm
            version: "21"
          - vendor: graalvm
            version: "25"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./java
          file: ./java/${{ matrix.vendor }}/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/images:java_${{ matrix.vendor }}_${{ matrix.version }}